AllCops:
  Exclude:
    - '**/Gemfile'
    - '**/Rakefile'
    - 'spec/**/*'

AllCops:
  RunRailsCops: true

StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Metrics/LineLength:
  Enabled: true
  Max: 120